# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-e0Qq9HTmWJxutyD6LCJX9vvLJvaU_f
"""

import pandas as pd

# Create data
data = {'A': [1, 2, 3, 4, 5,5]}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print("Data Frame:")
print(df)

# Sum of each column
print("\nSum of each column:")
print(df.sum())

# Mean of each column
print("\nMean of each column:")
print(df.mean())

# Median of each column
print("\nMedian of each column:")
print(df.median())

# Mode of each column
print("\nMode of each column:")
print(df.mode())

# Minimum value of each column
print("\nMinimum value of each column:")
print(df.min())

# Maximum value of each column
print("\nMaximum value of each column:")
print(df.max())

# Count of non-null entries of each column
print("\nCount of non-null entries of each column:")
print(df.count())

# Variance of each column
print("\nVariance of each column:")
print(df.var())

# Standard deviation of each column
print("\nStandard deviation of each column:")
print(df.std())